name: React App Deploy To Surge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 16
        
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
        
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./build bootcamp-2020-class-2.surge.sh --token ${{secrets.SURGE_TOKEN}}
